### ISSUE TITLE
Nom del projecte

### ISSUE THREAD

**Issue by dolorssala** [SkyGypsophila/KeyWork#2]
Podeu si us plau posar el vostre G2x- (on x sigui el valor del vostre grup) davant del nom del projecte?
Per nosaltres poder-los identificar i visualitzar en ordre alfabètic.

Gràcies
Dolors

**Comment by SkyGypsophila** [comment]
Feta. El nom de repositori és `G25-KeyWork`.

**Comment by SkyGypsophila** [comment]
> Feta. El nom de repositori `G25-KeyWork`.
